services:
  nxs:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      # Main nginx.conf avoids conf.d/default.conf being overwritten by image entrypoint (envsubst templates).
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./js:/var/www:ro
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true
